from yoyo import step

__depends__ = {'__init__'}

steps = [
    step(
        """
        CREATE TABLE IF NOT EXISTS products (
            id integer generated by default as identity primary key,
            name varchar(150) not null,
            description text,
            price numeric(10,2) not null check (price >= 0),
            is_available boolean not null default true,
            created_at timestamptz not null default now(),
            updated_at timestamptz not null default now()
        );

        CREATE OR REPLACE FUNCTION set_products_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER trigger_products_set_updated_at
        BEFORE UPDATE ON products
        FOR EACH ROW
        EXECUTE FUNCTION set_products_updated_at();
        """,
        """
        DROP TRIGGER IF EXISTS trigger_products_set_updated_at ON products;
        DROP FUNCTION IF EXISTS set_products_updated_at();
        DROP TABLE IF EXISTS products;
        """
    ),
]